### ISSUE TITLE
Use Perl, Ruby, PHP or shell command to process regex

### ISSUE THREAD

**Issue by SojournerOctocat** [seesolve/save-that-tweet#1]
I think Ruby, Perl and PHP (all of which come pre-installed on the Mac) can be used to process regular expressions. Look into these options (and possible version issues).

**Comment by seesolve** [comment]
Thanks to @emmagras, found out that Python isn't meant to be called from the command-line and won't be useful in this instance.

**Comment by kytrinyx** [comment]
For reference, this is the regex in question:

```
([A-Za-z0-9_]+)(?: - .+? - )(.+?)(?: - Retweeted by [A-Za-z0-9_]+)?(?: - [0-9]{1,2} [A-Z]{1}[a-z]{2} [0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2})(?: )?
```

What are some example inputs, and what is the desired output format?

**Comment by seesolve** [comment]
You're here? Amazing. After your smack down in the CodeNewbie Slack, you're the last participant I expected.


Some sample inputs:

"podmostom - Jonn Mostovoy - @seesolve use @mietek's thing. IIRC it automates sandboxes and makes cabal hell less visible. - 1 Apr 2015 19:49:32 "

"seesolve - sojourner hardeman - . @podmostom @mietek I'm scared. Halcyon looks perfect. I'm terrified, actually. How could it possibly live up to its promises? … Diving in. - Retweeted by mietek - 1 Apr 2015 19:52:36 "

"EggFreckles - Egg Freckles - I still use RSS.

(Retweet if true, favorite if false.) - Retweeted by dougscripts - 1 Apr 2015 19:11:00 "


Output format:

"RT @$1: $2"

**Comment by kytrinyx** [comment]
OK, so when the input is:

```
seesolve - sojourner hardeman - . @podmostom @mietek I'm scared. Halcyon looks perfect. I'm terrified, actually. How could it possibly live up to its promises? … Diving in. - Retweeted by mietek - 1 Apr 2015 19:52:36
```

Then the output is:

```
RT @seesolve: . @podmostom @mietek I'm scared. Halcyon looks perfect. I'm terrified, actually. How could it possibly live up to its promises? … Diving in.
```

Or did I map that incorrectly?

How about with this input?

```
podmostom - Jonn Mostovoy - @seesolve use @mietek's thing. IIRC it automates sandboxes and makes cabal hell less visible. - 1 Apr 2015 19:49:32
```

```
RT @podmostom: @seesolve use @mietek's thing. IIRC it automates sandboxes and makes cabal hell less visible.
```

?

It wasn't a smackdown. Your question came across as "do my work for me", but in retrospect it seems more like you just don't know enough about what's involved to ask the question that you meant to ask. I'm willing to help tease out the details.

**Comment by seesolve** [comment]
No. You had it right. This is do my work for me. I don't know enough about the command-line tools needed to write the syntax, and I am asking for someone to tell me that syntax.

And, yes, when I run my script those outputs you mapped are what I get.

**Comment by kytrinyx** [comment]
I don't mind at all giving you syntax for a specific thing (when I get home to my home computer I'll do a couple of small experiments and send you the result). The problem was that the question was missing enough information to answer it, and hence sounded like a much bigger question.

**Comment by seesolve** [comment]
Oh, okay. Thank you for helping me clarify the question.

**Comment by kytrinyx** [comment]
Here's a solution using ruby:


```bash
ruby -e "a,b=%q{TWEET}.match(/REGEX/).captures;puts %Q{RT @#{a}: #{b}}"
```

You should be able to run this in your terminal to verify:

```bash
ruby -e "a,b=%q{podmostom - Jonn Mostovoy - @seesolve use @mietek's thing. IIRC it automates sandboxes and makes cabal hell less visible. - 1 Apr 2015 19:49:32}.match(/([A-Za-z0-9_]+)(?: - .+? - )(.+?)(?: - Retweeted by [A-Za-z0-9_]+)?(?: - [0-9]{1,2} [A-Z]{1}[a-z]{2} [0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2})(?: )?/).captures;puts %Q{RT @#{a}: #{b}}"
```

**Comment by seesolve** [comment]
Yay! That works! I've updated the script. Thank you for your help!

I don't know if you're familiar with the Mac platform. Different versions of OS X will have different versions of Ruby pre-installed. Do you know if the command you gave me has different syntax in older versions of Ruby?

**Comment by kytrinyx** [comment]
I'm reasonably familiar with Mac. Let me try that in 1.8 which ships on Mavericks and older (I think)

**Comment by kytrinyx** [comment]
Yepp. It works in 1.8.7 which I think is the oldest version you need to worry about.

**Comment by seesolve** [comment]
I believe you're right about that. 10.7 uses Ruby 1.8.7 as well. Thank you for your help!

**Comment by kytrinyx** [comment]
My pleasure, glad you got it sorted!

**Comment by seesolve** [comment]
Getting an error with this tweet. Probably due to the LF/CR character in the middle of the tweet. I'll look into how Ruby parses regex.

````RT @JamesRisen: Finally, someone besides me is noticing
http://t.co/WSVqJLQZd2````

**Comment by kytrinyx** [comment]
I think "multiline regexes" should point you in the right direction.

**Comment by seesolve** [comment]
Eeeek! I got it! Thanks for the tip!

**Comment by kytrinyx** [comment]
Nice!
